# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 482f55d85919f9d1a527930799c4242696f685e7b98b109619bbece2ce9a67191cf98fa5215866b8de28bab22c34e7832dca0cbb5626877d695fc618b8504d59

test:
  secret_key_base: c6009a59ac5baa2f14be679d5d036be6bfd8024b0154ca689acb980b396eeeb28673d4fff24b3ce9dd88ed4c8c4f136ad9d9af569d08ff35fbef38ebc5fd2322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
